language: python

jobs:
  include:
    - stage: lint
      script:
        - pip install pylint
        - pylint wherepy

    - stage: deploy and test
      script:
        # install
        - pip install .
        # unit tests
        - cd tests
        - python -m unittest discover -s .
        # dummy module as we cannot install pyndicapi on Travis
        - touch pyndicapi.py
        # test packages importable
        - python -c 'import wherepy'
        - python -c 'import wherepy.gui'
        - python -c 'import wherepy.io'
        - python -c 'from wherepy.track import Tracker'
        - python -c 'from wherepy.track import ToolPose'
