language: python

script:
  # run unit tests
  - python -m unittest discover -s "tests"

  # test installation
  - pip install .
  - python -c 'import wherepy'
  - python -c 'import wherepy.app'
  - python -c 'import wherepy.gui'
  - python -c 'import wherepy.io'
  - python -c 'import wherepy.track'

  # test console scripts
  - wherepy-collector-gui --help
  - wherepy-collector-cli --help
