language: python

jobs:
  include:
    - stage: unit tests
      script: python -m unittest discover -s 'tests'

    - stage: deploy to staging
      script:
        - pip install .
        - python -c 'import wherepy'
        - python -c 'import wherepy.app'
        - python -c 'import wherepy.gui'
        - python -c 'import wherepy.io'
        - python -c 'import wherepy.track'

    - stage: test staging
      script:
        - wherepy-collector-gui --help
        - wherepy-collector-cli --help
