language: python

jobs:
  include:
    - stage: unit tests
      script: python -m unittest discover -s 'tests'

    - stage: test components callable
      script:
        # install
        - pip install .
        # test packages importable
        - python -c 'import wherepy'
        - python -c 'import wherepy.app'
        - python -c 'import wherepy.gui'
        - python -c 'import wherepy.io'
        - python -c 'import wherepy.track'
        # test console scripts callable
        - wherepy-collector-gui --help
        - wherepy-collector-cli --help
