language: python

script:
  # test installation
  - pip install .
  - python -c 'import wherepy'
  - python -c 'import wherepy.app'
  - python -c 'import wherepy.gui'
  - python -c 'import wherepy.io'
  - python -c 'import wherepy.track'
